included:
- Tidify

line_length: 200

disabled_rules:
- function_body_length
- cyclomatic_complexity
- function_parameter_count
- identifier_name
- file_length
- type_body_length
- large_tuple
- trailing_comma
- comment_spacing

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- explicit_init
- extension_access_modifier
- fatal_error_message
- first_where
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- nimble_operator
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- single_test_class
- sorted_first_last
- sorted_imports
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition

type_name:
  max_length: 60

number_separator:
  minimum_length: 5

nesting:
  type_level: 3
