# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Tidify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tidify
    pod 'SwiftLint'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxAppState'
    pod 'Moya/RxSwift'
    pod 'SnapKit'
    pod 'Then'
    pod 'R.swift'
    pod 'RxKakaoSDK'
    pod 'Kingfisher'
    pod 'SwiftLinkPreview'

  target 'TidifyTests' do
      inherit! :search_paths
      
      pod 'Quick'
      pod 'Nimble'
  end
end
