# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tidify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tidify
    pod 'SwiftLint'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxAppState'
    pod 'Moya/RxSwift'
    pod 'SnapKit'
    pod 'Then'
    pod 'R.swift'
end
